[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "CodingAgent"
version = "0.1.0"
description = "Simple Coding Agent"
authors = [{ name = "Xiyuan Yang", email = "yangxiyan@sjtu.edu.cn" }]
readme = "README.md"
requires-python = ">=3.8"
dependencies = []

[project.scripts]
coding_agent="CodingAgent.main:main"


[tool.setuptools]
include-package-data = true


[tool.setuptools.packages.find]
where = ["."]
exclude = [
    "test*",
    "log*",
    "__pycache__*",
]

[tool.setuptools.package-data]
"CodingAgent" = ["config.yaml"]
